apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  metrics:
    - type: External
      external:
        metric:
          name: test-metric
          selector:
            matchLabels:
              container: nginx
        target:
          averageValue: 50
          type: AverageValue
