apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: custom-metrics-apiserver
  name: custom-metrics-apiserver
  namespace: custom-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  template:
    metadata:
      name: custom-metrics-apiserver
      labels:
        app: custom-metrics-apiserver
        version: "5"
    spec:
      serviceAccountName: custom-metrics-apiserver
      containers:
      - name: custom-metrics-apiserver
        image: fpetkovski/prometheus-adapter
        imagePullPolicy: IfNotPresent
        args:
        - --secure-port=6443
        - --tls-cert-file=/var/run/tls/tls.crt
        - --tls-private-key-file=/var/run/tls/tls.key
        ports:
        - containerPort: 6443
        volumeMounts:
        - mountPath: /var/run/tls
          name: tls
      volumes:
      - name: tls
        emptyDir: {}
